receitas2019/Controllers/AdmReceitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Receitas2019.Core.Context;
using Receitas2019.Core.Models;

namespace Receitas2019.Web.Controllers
{
    [Authorize]
    public class AdmReceitasController : Controller
    {
        private readonly AppDbContext _context;

        public AdmReceitasController(AppDbContext context)
        {
            _context = context;
        }

        // GET: AdministracaoReceitas
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Receitas.Include(r => r.Categoria);
            return View(await appDbContext.ToListAsync());
        }

        // GET: AdministracaoReceitas/Create
        public IActionResult Create()
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "Id", "Id");
            return View();
        }

        // POST: AdministracaoReceitas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,ModoDePreparo,Ingredientes,TempoDePreparo,Imagem,CategoriaId,Tag")] Receita receita)
        {
            if (ModelState.IsValid)
            {
                _context.Add(receita);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "Id", "Id", receita.CategoriaId);
            return View(receita);
        }

        // GET: AdministracaoReceitas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receita = await _context.Receitas.FindAsync(id);
            if (receita == null)
            {
                return NotFound();
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "Id", "Id", receita.CategoriaId);
            return View(receita);
        }

        // POST: AdministracaoReceitas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,ModoDePreparo,Ingredientes,TempoDePreparo,Imagem,CategoriaId,Tag")] Receita receita)
        {
            if (id != receita.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(receita);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReceitaExists(receita.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "Id", "Id", receita.CategoriaId);
            return View(receita);
        }

        // GET: AdministracaoReceitas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receita = await _context.Receitas
                .Include(r => r.Categoria)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (receita == null)
            {
                return NotFound();
            }

            return View(receita);
        }

        // POST: AdministracaoReceitas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var receita = await _context.Receitas.FindAsync(id);
            _context.Receitas.Remove(receita);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReceitaExists(int id)
        {
            return _context.Receitas.Any(e => e.Id == id);
        }
    }
}

receitas2019/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Receitas2019.Web.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

receitas2019/Controllers/ReceitaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using receitas2019.Repositories.Interface;
using Receitas2019.Core.Models;
using Receitas2019.Web.ViewModels;

namespace receitas2019.Controllers
{
    public class ReceitaController : Controller
    {
        private readonly IReceitaRepository _receitaRepository;

        public ReceitaController(IReceitaRepository receitaRepository)
        {
            _receitaRepository = receitaRepository;
        }

        public IActionResult List(string categoria)
        {
            string _categoria = categoria;
            IEnumerable<Receita> receitas;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                receitas = _receitaRepository.Receitas.OrderBy(r => r.Id);
                categoriaAtual = "Todos as receitas";
            }
            else
            {
                receitas = _receitaRepository.Receitas.Where(r => r.CategoriaId.Equals(categoria)).OrderBy(r => r.Nome);

                if (string.Equals("Doce", _categoria, StringComparison.OrdinalIgnoreCase))
                    receitas = _receitaRepository.Receitas.Where(r => r.CategoriaId.Equals(1)).OrderBy(r => r.Nome);
                else
                    receitas = _receitaRepository.Receitas.Where(r => r.CategoriaId.Equals(2)).OrderBy(r => r.Nome);

                categoriaAtual = categoria;
            }

            var receitasListViewModel = new ReceitasListViewModel
            {
                Receitas = receitas,
                CategoriaAtual = categoriaAtual
            };

            return View(receitasListViewModel);
        }
        public ViewResult Details(int receitaId)
        {
            var receita = _receitaRepository.Receitas.FirstOrDefault(r => r.Id == receitaId);
            if (receita == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(receita);
        }

        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Receita> receitas;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                receitas = _receitaRepository.Receitas.OrderBy(r => r.Id);
            }
            else
            {
                receitas = _receitaRepository.Receitas.Where(p => p.Tag.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Receita/List.cshtml", new ReceitasListViewModel { Receitas = receitas, CategoriaAtual = "Todos as receitas" });
        }
    }
}

receitas2019/Views/Shared/_Carrossel.cshtml
<div id="carouselExampleIndicators" class="carousel slide" style="align-items:center; justify-content:center;border:none; border-radius:7px" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol><br /><br /><br /><br />
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" width="300" height="300" src="~/images/Carrossel1.jpg" alt="Primeiro Slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" width="300" height="300" src="~/images/Carrossel2.jpg" alt="Segundo Slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" width="300" height="300" src="~/images/Carrossel3.gif" alt="Terceiro Slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
    </a>
</div>

receitas2019/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Receita Manera</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark text-white">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Receita Manera</a>
                <div class="navbar navbar-expand-sm">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @await Component.InvokeAsync("CategoriaMenu")
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Contato" asp-action="Index">Fale Conosco</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown">
                                <a class="nav-link text-white" asp-controller="AdmReceitas" asp-action="Index" data-toggle="dropdown">
                                    Administração<b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="nav-link text-dark" asp-controller="AdmReceitas" asp-action="Index">Receitas</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
                @await Html.PartialAsync("_LoginPartial")
                
                <form class="navbar-form navbar-right text-white" asp-controller="Receita" asp-action="Search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Procurar Receitas" name="searchString" value="@ViewData["searchString"]">
                    </div>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Receita Manera - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

receitas2019/Views/Shared/_ReceitaResumo.cshtml
@model Receita

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <a asp-controller="Receita" asp-action="Details" asp-route-receitaId="@Model.Id"><img src="@Model.Imagem" class="rounded" alt="" width="300" /></a>
    </div>
    <div class="caption">
        <h3>
            <a asp-controller="Receita" asp-action="Details" asp-route-receitaId="@Model.Id">@Model.Nome</a>
        </h3><br />
        <h5><img width="30" height="30" src="~/images/relogio.png"> @Model.TempoDePreparo </h5>
    </div>
</div>